table Date
	lineageTag: 3a43aa04-31f0-4a0d-b671-d73a5de20faf
	dataCategory: Time

	measure _ShowValueForDates =
			
			VAR __LastDateWithData =
			    CALCULATE (
			        MAXX ( { MAX ( 'DimData'[Data] ), MAX ( 'DimLotto'[DataProduzione] ), MAX ( 'DimLotto'[DataScadenza] ), MAX ( 'FattoProduzione'[Data] ), MAX ( 'FattoMagazzino'[DataSnapshot] ), MAX ( 'FattoMagazzino'[Scadenza Lotto] ), MAX ( 'FattoRaccoltaLatte'[Data] ), MAX ( 'FattoVendite'[Data] ) }, ''[Value] ),
			        REMOVEFILTERS ()
			    )
			VAR __FirstDateVisible =
			    MIN ( 'Date'[Date] )
			VAR __Result =
			    __FirstDateVisible <= __LastDateWithData
			RETURN
			    __Result
		isHidden
		displayFolder: Hidden Time Intelligence
		lineageTag: 21f405fc-be5d-4481-befc-935e40854734

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	column Date
		isKey
		formatString: dd/mm/yyyy
		lineageTag: 03a95055-e9c6-4c5a-b212-ad2eb868c74e
		dataCategory: PaddedDateTableDates
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Date]

		annotation SQLBI_AttributeTypes = Date

	column Year
		lineageTag: 95a064d1-8a05-4c7a-aa41-c64c2bcb419f
		dataCategory: Years
		summarizeBy: sum
		isNameInferred
		sourceColumn: DateAutoTemplate[Year]

		annotation SummarizationSetBy = Automatic

	column 'Year Quarter Number'
		isHidden
		lineageTag: 1ca30e45-b9f3-481d-9f97-af8339833d52
		dataCategory: Quarters
		summarizeBy: sum
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Quarter Number]

		annotation SummarizationSetBy = Automatic

	column 'Year Quarter'
		lineageTag: 3514b5a0-c0e5-41f9-af81-e0c9d6a7e80a
		dataCategory: Quarters
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Quarter]
		sortByColumn: 'Year Quarter Number'

	column Quarter
		lineageTag: 66b2e585-41d5-4aa9-80f0-1b1bdc848480
		dataCategory: QuarterOfYear
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Quarter]

	column 'Year Month'
		lineageTag: 23fe8cb7-ea78-4808-a634-3d3805512d99
		dataCategory: Months
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Month]
		sortByColumn: 'Year Month Number'

	column 'Year Month Number'
		isHidden
		lineageTag: 148edba3-5672-4611-85b5-c0b8928325ae
		dataCategory: Months
		summarizeBy: sum
		isNameInferred
		sourceColumn: DateAutoTemplate[Year Month Number]

		annotation SummarizationSetBy = Automatic

	column Month
		lineageTag: 19faff59-3f73-49c9-a24a-9d62f3f2af88
		dataCategory: MonthOfYear
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Month]
		sortByColumn: 'Month Number'

	column 'Month Number'
		isHidden
		lineageTag: 6df0934f-f128-48c7-8492-761b116225f7
		dataCategory: MonthOfYear
		summarizeBy: sum
		isNameInferred
		sourceColumn: DateAutoTemplate[Month Number]

		annotation SummarizationSetBy = Automatic

	column 'Day of Week Number'
		isHidden
		lineageTag: 008f9e7c-3a13-4ec1-baa8-f2aa4d484a99
		dataCategory: DayOfWeek
		summarizeBy: sum
		isNameInferred
		sourceColumn: DateAutoTemplate[Day of Week Number]

		annotation SQLBI_AttributeTypes = DayOfWeek

		annotation SQLBI_FilterSafe = True

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		lineageTag: fdec4190-02b0-4c19-87a0-344c35485211
		dataCategory: DayOfWeek
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[Day of Week]
		sortByColumn: 'Day of Week Number'

		annotation SQLBI_FilterSafe = True

	column DateWithTransactions
		isHidden
		lineageTag: b066a024-3c32-482f-ac07-d5ccf6e3bed2
		summarizeBy: none
		isNameInferred
		sourceColumn: DateAutoTemplate[DateWithTransactions]

		annotation SQLBI_AttributeTypes = DateDuration

	hierarchy Calendar
		lineageTag: 512d794f-8cf8-464f-83f6-b63144247fc7

		level Year
			lineageTag: 333e16ac-407b-44fc-9e73-04ffb00dd2f2
			column: Year

		level Month
			lineageTag: 50375c8a-0eb1-414a-980a-045b070d3ff3
			column: 'Year Month'

		level Date
			lineageTag: 258b40df-d403-4978-9a2c-748c8c9ce780
			column: Date

	partition Date = calculated
		mode: import
		source = DateAutoTemplate

	annotation SQLBI_Template = Dates

	annotation SQLBI_TemplateTable = Date

	annotation SQLBI_CalendarType = Calendar

