table DimCanale
	lineageTag: 23fba7a9-766a-4296-b8ab-7cee5507d63f

	column CanaleID
		dataType: int64
		formatString: 0
		lineageTag: 5b6396d7-2096-4bdf-bc32-288c17b28e7d
		summarizeBy: none
		sourceColumn: CanaleID

		annotation SummarizationSetBy = Automatic

	column Canale
		dataType: string
		lineageTag: 860d8b27-1a42-440c-bb20-f295a2c48bf5
		summarizeBy: none
		sourceColumn: Canale

		annotation SummarizationSetBy = Automatic

	partition DimCanale = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\CarmineCheca\Desktop\CorsoGarofalo_BI\Caseificio_Demo_Dataset.xlsx"), null, true),
				    DimCanale_Sheet = Origine{[Item="DimCanale",Kind="Sheet"]}[Data],
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(DimCanale_Sheet, [PromoteAllScalars=true]),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"CanaleID", Int64.Type}, {"Canale", type text}})
				in
				    #"Modificato tipo"

	annotation PBI_ResultType = Table

