table DimCliente
	lineageTag: a8908303-0a4e-495b-8e44-706da1c7df5a

	column ClienteID
		dataType: int64
		formatString: 0
		lineageTag: 8e39add4-756d-43e0-9a4d-12608ff266c2
		summarizeBy: none
		sourceColumn: ClienteID

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: string
		lineageTag: 8dc20fa2-c2b0-427f-af2e-e82c1b22dfa1
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Insegna
		dataType: string
		lineageTag: 862bab50-8e1a-4482-8918-e9d0aaafdf0f
		summarizeBy: none
		sourceColumn: Insegna

		annotation SummarizationSetBy = Automatic

	column Zona
		dataType: string
		lineageTag: a49e42cc-30fb-4428-8db8-f04368ae90b3
		summarizeBy: none
		sourceColumn: Zona

		annotation SummarizationSetBy = Automatic

	partition DimCliente = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\CarmineCheca\Desktop\CorsoGarofalo_BI\Caseificio_Demo_Dataset.xlsx"), null, true),
				    DimCliente_Sheet = Origine{[Item="DimCliente",Kind="Sheet"]}[Data],
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(DimCliente_Sheet, [PromoteAllScalars=true]),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"ClienteID", Int64.Type}, {"Cliente", type text}, {"Insegna", type text}, {"Zona", type text}}),
				    #"Testo troncato" = Table.TransformColumns(#"Modificato tipo",{{"Insegna", Text.Trim, type text}}),
				    #"Pulito testo" = Table.TransformColumns(#"Testo troncato",{{"Insegna", Text.Clean, type text}}),
				    #"Convertita in maiuscolo ogni parola" = Table.TransformColumns(#"Pulito testo",{{"Insegna", Text.Proper, type text}})
				in
				    #"Convertita in maiuscolo ogni parola"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigazione

