table DimFornitore
	lineageTag: 4d8ed183-b39b-4841-b108-3330e8089c4f

	column FornitoreID
		dataType: int64
		formatString: 0
		lineageTag: 9aa6e2d8-7ca7-4e9e-b54e-158d303a5537
		summarizeBy: none
		sourceColumn: FornitoreID

		annotation SummarizationSetBy = Automatic

	column Fornitore
		dataType: string
		lineageTag: 72126553-1778-4085-837f-5d6aee2e90ce
		summarizeBy: none
		sourceColumn: Fornitore

		annotation SummarizationSetBy = Automatic

	column Zona
		dataType: string
		lineageTag: 44ed13ac-25ad-4b87-833e-8dfd5fae7afa
		summarizeBy: none
		sourceColumn: Zona

		annotation SummarizationSetBy = Automatic

	partition DimFornitore = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\CarmineCheca\Desktop\CorsoGarofalo_BI\Caseificio_Demo_Dataset.xlsx"), null, true),
				    DimFornitore_Sheet = Origine{[Item="DimFornitore",Kind="Sheet"]}[Data],
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(DimFornitore_Sheet, [PromoteAllScalars=true]),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"FornitoreID", Int64.Type}, {"Fornitore", type text}, {"Zona", type text}})
				in
				    #"Modificato tipo"

	annotation PBI_ResultType = Table

