table DimLotto
	lineageTag: 4dd33da7-f5f6-40dc-8fcf-c5d8b5d2a110

	column LottoID
		dataType: int64
		formatString: 0
		lineageTag: 897bdff3-4953-4980-9b42-e8118276a069
		summarizeBy: none
		sourceColumn: LottoID

		annotation SummarizationSetBy = Automatic

	column Lotto
		dataType: string
		lineageTag: 6f84bdfb-c807-4d23-b2e1-44211128c7fc
		summarizeBy: none
		sourceColumn: Lotto

		annotation SummarizationSetBy = Automatic

	column DataProduzione
		dataType: dateTime
		formatString: Long Date
		lineageTag: aa44cb2f-801e-4ac8-bf15-f93e7f88509b
		summarizeBy: none
		sourceColumn: DataProduzione

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DataScadenza
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3aaebc7c-e46a-46c9-aded-5fbf40609a6d
		summarizeBy: none
		sourceColumn: DataScadenza

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ReferenzaID
		dataType: int64
		formatString: 0
		lineageTag: c7ae08c7-0fc5-468a-8fd5-24b42e93b234
		summarizeBy: count
		sourceColumn: ReferenzaID

		annotation SummarizationSetBy = Automatic

	column StabilimentoID
		dataType: int64
		formatString: 0
		lineageTag: 2ffb4b26-5bed-4c98-8e50-616cccd6c0b7
		summarizeBy: none
		sourceColumn: StabilimentoID

		annotation SummarizationSetBy = Automatic

	partition DimLotto = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\CarmineCheca\Desktop\CorsoGarofalo_BI\Caseificio_Demo_Dataset.xlsx"), null, true),
				    DimLotto_Sheet = Origine{[Item="DimLotto",Kind="Sheet"]}[Data],
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(DimLotto_Sheet, [PromoteAllScalars=true]),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"LottoID", Int64.Type}, {"Lotto", type text}, {"DataProduzione", type date}, {"DataScadenza", type date}, {"ReferenzaID", Int64.Type}, {"StabilimentoID", Int64.Type}})
				in
				    #"Modificato tipo"

	annotation PBI_ResultType = Table

