table DimReferenza
	lineageTag: 802b65da-e867-4e16-8189-49b4990a0bc7

	column ReferenzaID
		dataType: int64
		formatString: 0
		lineageTag: 2030bee6-a66f-48d0-bd1e-8e986981dfed
		summarizeBy: none
		sourceColumn: ReferenzaID

		annotation SummarizationSetBy = Automatic

	column Referenza
		dataType: string
		lineageTag: 116356b2-3057-44c0-b1b8-6bdc450bd296
		summarizeBy: none
		sourceColumn: Referenza

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: a77a7aa1-939e-4457-ae58-98b94001b597
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column GiorniStagionatura
		dataType: int64
		formatString: 0
		lineageTag: 6d3871b6-efaa-4180-aa3f-b4d10343ad61
		summarizeBy: sum
		sourceColumn: GiorniStagionatura

		annotation SummarizationSetBy = Automatic

	column UM
		dataType: string
		lineageTag: 9b450102-48c2-4bcd-a990-468c742381c7
		summarizeBy: none
		sourceColumn: UM

		annotation SummarizationSetBy = Automatic

	column PrezzoListino
		dataType: double
		lineageTag: 9fa47e1e-b118-49b0-9442-6305a17fed2b
		summarizeBy: sum
		sourceColumn: PrezzoListino

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DimReferenza = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\CarmineCheca\Desktop\CorsoGarofalo_BI\Caseificio_Demo_Dataset.xlsx"), null, true),
				    DimReferenza_Sheet = Origine{[Item="DimReferenza",Kind="Sheet"]}[Data],
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(DimReferenza_Sheet, [PromoteAllScalars=true]),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"ReferenzaID", Int64.Type}, {"Referenza", type text}, {"Categoria", type text}, {"GiorniStagionatura", Int64.Type}, {"UM", type text}, {"PrezzoListino", type number}})
				in
				    #"Modificato tipo"

	annotation PBI_ResultType = Table

