table DimStabilimento
	lineageTag: 10adc5e6-80aa-4aed-89f1-74d34b7dc381

	column StabilimentoID
		dataType: int64
		formatString: 0
		lineageTag: 3b903664-ebd1-42b2-952e-fc45b584b528
		summarizeBy: none
		sourceColumn: StabilimentoID

		annotation SummarizationSetBy = Automatic

	column Stabilimento
		dataType: string
		lineageTag: 1a2f5116-81c1-4658-9ddb-4121b9acbf6f
		summarizeBy: none
		sourceColumn: Stabilimento

		annotation SummarizationSetBy = Automatic

	column Linea
		dataType: string
		lineageTag: 9d4e25b5-9b5e-4dc0-bcd7-289151e050ca
		summarizeBy: none
		sourceColumn: Linea

		annotation SummarizationSetBy = Automatic

	column EmailResponsabile
		dataType: string
		lineageTag: 97a71e9a-aa60-4aff-8435-5a6e40405daf
		summarizeBy: none
		sourceColumn: EmailResponsabile

		annotation SummarizationSetBy = Automatic

	partition DimStabilimento = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\CarmineCheca\Desktop\CorsoGarofalo_BI\Caseificio_Demo_Dataset.xlsx"), null, true),
				    DimStabilimento_Sheet = Origine{[Item="DimStabilimento",Kind="Sheet"]}[Data],
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(DimStabilimento_Sheet, [PromoteAllScalars=true]),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"StabilimentoID", Int64.Type}, {"Stabilimento", type text}, {"Linea", type text}, {"EmailResponsabile", type text}})
				in
				    #"Modificato tipo"

	annotation PBI_ResultType = Table

