table FattoRaccoltaLatte
	lineageTag: eb6b6421-dd27-4157-8877-572790b3ebd8

	column RigaID
		dataType: string
		lineageTag: aa2177be-1512-4c74-8521-ee4d3097837c
		summarizeBy: none
		sourceColumn: RigaID

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5033bf69-f618-453e-8a24-1d4c84292252
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FornitoreID
		dataType: string
		lineageTag: 72f206e2-8581-4854-9b2d-b3c67d610a9a
		summarizeBy: none
		sourceColumn: FornitoreID

		annotation SummarizationSetBy = Automatic

	column StabilimentoID
		dataType: string
		lineageTag: 37fec9a5-2033-4101-b6bb-c474836c9d70
		summarizeBy: none
		sourceColumn: StabilimentoID

		annotation SummarizationSetBy = Automatic

	column Litri
		dataType: int64
		formatString: 0
		lineageTag: 82df680a-cf99-4dd4-859f-14bd2cf27968
		summarizeBy: sum
		sourceColumn: Litri

		annotation SummarizationSetBy = Automatic

	column PercGrasso
		dataType: double
		lineageTag: b29ca05e-7923-4f04-843b-39631acef897
		summarizeBy: sum
		sourceColumn: PercGrasso

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PercProteine
		dataType: string
		lineageTag: 09bc061b-92a4-4756-a648-0d28fcb70c33
		summarizeBy: none
		sourceColumn: PercProteine

		annotation SummarizationSetBy = Automatic

	partition FattoRaccoltaLatte = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\CarmineCheca\Desktop\CorsoGarofalo_BI\Caseificio_Demo_Dataset.xlsx"), null, true),
				    FattoRaccoltaLatte_Sheet = Origine{[Item="FattoRaccoltaLatte",Kind="Sheet"]}[Data],
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(FattoRaccoltaLatte_Sheet, [PromoteAllScalars=true]),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"Data", type date}}),
				    #"Modificato tipo con impostazioni locali" = Table.TransformColumnTypes(#"Modificato tipo", {{"Data", type date}}, "it-IT"),
				    #"Modificato tipo1" = Table.TransformColumnTypes(#"Modificato tipo con impostazioni locali",{{"Litri", Int64.Type}, {"PercGrasso", type number}}),
				    #"Rimossi duplicati" = Table.Distinct(#"Modificato tipo1", {"RigaID"})
				in
				    #"Rimossi duplicati"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigazione

