table FattoMagazzino
	lineageTag: 2470b5df-a44d-4d74-b4ea-43c25f34b7f6

	column RigaID
		dataType: int64
		formatString: 0
		lineageTag: ade92644-980d-4df7-b8d5-0d8d1d8c6a6c
		summarizeBy: count
		sourceColumn: RigaID

		annotation SummarizationSetBy = Automatic

	column DataSnapshot
		dataType: dateTime
		formatString: Long Date
		lineageTag: 124f177a-fbc9-4c0c-976a-cd1b46c0f1e7
		summarizeBy: none
		sourceColumn: DataSnapshot

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LottoID
		dataType: int64
		formatString: 0
		lineageTag: 7156dc55-fc10-40e4-9fa0-84a1fa070dac
		summarizeBy: none
		sourceColumn: LottoID

		annotation SummarizationSetBy = Automatic

	column ReferenzaID
		dataType: int64
		formatString: 0
		lineageTag: c7f3996b-d12a-4cff-83c4-fb73ef50e8e7
		summarizeBy: count
		sourceColumn: ReferenzaID

		annotation SummarizationSetBy = Automatic

	column GiacenzaKg
		dataType: double
		lineageTag: fe12fcef-e5af-45f9-a750-b032dfd18864
		summarizeBy: sum
		sourceColumn: GiacenzaKg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ValoreFIFO
		dataType: double
		lineageTag: 6ef95311-5e8a-41d4-bf2a-8c60b9572ee3
		summarizeBy: sum
		sourceColumn: ValoreFIFO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Scadenza Lotto' = RELATED(DimLotto[DataScadenza])
		formatString: General Date
		lineageTag: 8cec8b12-ae21-4b9f-93fc-55d78fa5cb22
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition FattoMagazzino = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\CarmineCheca\Desktop\CorsoGarofalo_BI\Caseificio_Demo_Dataset.xlsx"), null, true),
				    FattoMagazzino_Sheet = Origine{[Item="FattoMagazzino",Kind="Sheet"]}[Data],
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(FattoMagazzino_Sheet, [PromoteAllScalars=true]),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"RigaID", Int64.Type}, {"DataSnapshot", type date}, {"LottoID", Int64.Type}, {"ReferenzaID", Int64.Type}, {"GiacenzaKg", type number}, {"ValoreFIFO", type number}})
				in
				    #"Modificato tipo"

	annotation PBI_ResultType = Table

