table FattoProduzione
	lineageTag: 4d968343-9af5-42e9-8bcf-2011fe367f27

	column RigaID
		dataType: int64
		formatString: 0
		lineageTag: 90a9e8cb-c29f-4a8c-a9ba-f8b75a32a140
		summarizeBy: count
		sourceColumn: RigaID

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 035b7c77-4c21-4ef8-b0d9-675cd70f118b
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LottoID
		dataType: int64
		formatString: 0
		lineageTag: a4c85fac-e376-4fac-8b94-27e2a153e77b
		summarizeBy: count
		sourceColumn: LottoID

		annotation SummarizationSetBy = Automatic

	column ReferenzaID
		dataType: int64
		formatString: 0
		lineageTag: 1617bcd0-4596-41fe-8a5b-056c41fd0fc1
		summarizeBy: none
		sourceColumn: ReferenzaID

		annotation SummarizationSetBy = Automatic

	column StabilimentoID
		dataType: int64
		formatString: 0
		lineageTag: f4dd681e-c0f8-451f-8b07-d339d6ee1a4e
		summarizeBy: count
		sourceColumn: StabilimentoID

		annotation SummarizationSetBy = Automatic

	column KgProdotti
		dataType: double
		lineageTag: 4de00b22-db45-4a68-a694-c9cdc3d29ca3
		summarizeBy: sum
		sourceColumn: KgProdotti

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LitriLatteImpiegati
		dataType: int64
		formatString: 0
		lineageTag: bfa50dea-ede7-4668-b298-d2e9ddb4fceb
		summarizeBy: sum
		sourceColumn: LitriLatteImpiegati

		annotation SummarizationSetBy = Automatic

	column Scarti
		dataType: double
		lineageTag: 76e9bfc5-531f-42af-beea-efe9c64e3c9c
		summarizeBy: sum
		sourceColumn: Scarti

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FattoProduzione = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\CarmineCheca\Desktop\CorsoGarofalo_BI\Caseificio_Demo_Dataset.xlsx"), null, true),
				    FattoProduzione_Sheet = Origine{[Item="FattoProduzione",Kind="Sheet"]}[Data],
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(FattoProduzione_Sheet, [PromoteAllScalars=true]),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"RigaID", Int64.Type}, {"Data", type date}, {"LottoID", Int64.Type}, {"ReferenzaID", Int64.Type}, {"StabilimentoID", Int64.Type}, {"KgProdotti", type number}, {"LitriLatteImpiegati", Int64.Type}, {"Scarti", type number}})
				in
				    #"Modificato tipo"

	annotation PBI_ResultType = Table

