table FattoVendite
	lineageTag: 90907f24-59dc-470f-8250-dacd81486a4c

	column RigaID
		dataType: int64
		formatString: 0
		lineageTag: 4bedd313-860a-4ebf-b666-51b991e3d4ed
		summarizeBy: count
		sourceColumn: RigaID

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 88e24797-4edc-4189-bdc6-ae99489305b3
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ClienteID
		dataType: int64
		formatString: 0
		lineageTag: e2013803-8acb-4acc-8d19-e6a199be3cab
		summarizeBy: none
		sourceColumn: ClienteID

		annotation SummarizationSetBy = Automatic

	column CanaleID
		dataType: int64
		formatString: 0
		lineageTag: 57736264-a19c-4377-a56a-ca2aada89791
		summarizeBy: none
		sourceColumn: CanaleID

		annotation SummarizationSetBy = Automatic

	column ReferenzaID
		dataType: int64
		formatString: 0
		lineageTag: 2a4206df-0427-423e-bfd1-cec03f778a58
		summarizeBy: none
		sourceColumn: ReferenzaID

		annotation SummarizationSetBy = Automatic

	column LottoID
		dataType: int64
		formatString: 0
		lineageTag: 61499a07-f8cb-4b8c-aeb6-55999f690774
		summarizeBy: none
		sourceColumn: LottoID

		annotation SummarizationSetBy = Automatic

	column KgVenduti
		dataType: double
		lineageTag: 598a3954-344e-46b5-97ad-836bfe02ba12
		summarizeBy: sum
		sourceColumn: KgVenduti

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ricavo
		dataType: double
		lineageTag: c1547f44-2912-4a90-ae44-8ee69776464d
		summarizeBy: sum
		sourceColumn: Ricavo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Costo
		dataType: double
		lineageTag: 83ce33fc-e91b-422b-8624-ea0c66997549
		summarizeBy: sum
		sourceColumn: Costo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FattoVendite = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\CarmineCheca\Desktop\CorsoGarofalo_BI\Caseificio_Demo_Dataset.xlsx"), null, true),
				    FattoVendite_Sheet = Origine{[Item="FattoVendite",Kind="Sheet"]}[Data],
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(FattoVendite_Sheet, [PromoteAllScalars=true]),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"RigaID", Int64.Type}, {"Data", type date}, {"ClienteID", Int64.Type}, {"CanaleID", Int64.Type}, {"ReferenzaID", Int64.Type}, {"LottoID", Int64.Type}, {"KgVenduti", type number}, {"Ricavo", type number}, {"Costo", type number}})
				in
				    #"Modificato tipo"

	annotation PBI_ResultType = Table

