table Misure
	lineageTag: 940864fe-1c82-4307-82a5-cb5bd253baa3

	measure Vendite =
			
			SUM(FattoVendite[Ricavo])
		lineageTag: cb1c1019-d467-41a0-b276-4894caa63d53

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Costo del venduto' =
			
			SUM(FattoVendite[Costo])
		lineageTag: 0f81c2f9-f79a-4cbc-b30b-cc9512ed786b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Margine = [Vendite]-[Costo del venduto]
		lineageTag: 7f99be66-d342-417d-98a6-952fd3fc6a31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Margine %' = DIVIDE([Margine],[Vendite],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c066783c-ec84-446c-b6da-63e0b2ed1ef1

	measure 'Vendite Anno precedente' = CALCULATE([Vendite],SAMEPERIODLASTYEAR('Date'[Date]))
		lineageTag: 40b5c0c0-911e-4daf-9dd7-d5f7025e3df6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Vendite YoY %' =
			
			DIVIDE([Vendite]-[Vendite Anno precedente],[Vendite Anno precedente],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: fce1ab4e-a99c-41a6-b2a7-95853272b6e2

	measure 'Lotti in scadenza 30gg' =
			
			CALCULATE(DISTINCTCOUNT(DimLotto[Lotto]),FILTER(DimLotto,DimLotto[DataScadenza]>= TODAY() &&
			DimLotto[DataScadenza]<= TODAY()+30))
		formatString: 0
		lineageTag: 6d055496-7090-4a2f-9d28-77dcaed6f644

	measure 'Lotti in magazzino scadenza 30gg' =
			
			CALCULATE(DISTINCTCOUNT(FattoMagazzino[Scadenza Lotto]),FILTER(DimLotto,DimLotto[DataScadenza]>= TODAY() &&
			DimLotto[DataScadenza]<= TODAY()+30))
		formatString: 0
		lineageTag: 80f704dd-8e77-433f-8eeb-99174c72ab71

	measure 'YTD Vendite' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite],
			        DATESYTD ( 'Date'[Date] )
			    )
			)
		displayFolder: Time intelligence\To-date total\Vendite
		lineageTag: 8f44a1c9-fa80-404b-a83f-c830a28e039f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Vendite' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite],
			        DATESQTD ( 'Date'[Date] )
			    )
			)
		displayFolder: Time intelligence\To-date total\Vendite
		lineageTag: 43de867b-14a1-4a66-84f0-e7f7d1453527

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Vendite' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite],
			        DATESMTD ( 'Date'[Date] )
			    )
			)
		displayFolder: Time intelligence\To-date total\Vendite
		lineageTag: 63cef29d-9732-4b4e-8b19-e83bd05d5344

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Vendite' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, YEAR ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\Growth\Vendite
		lineageTag: 940e7449-0782-4645-b3bc-d25dacbf5d97

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Vendite' =
			
			VAR __ValueCurrentPeriod = [Vendite]
			VAR __ValuePreviousPeriod = [PY Vendite]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth\Vendite
		lineageTag: 533535b2-e9f4-481f-92df-665825897932

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Vendite' = ```
			
			DIVIDE ( 
			    [YOY Vendite],
			    [PY Vendite]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Vendite
		lineageTag: de6a4696-2c22-454f-a2cb-46e36e02ec99

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Vendite' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, QUARTER ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\Growth\Vendite
		lineageTag: 19755cae-4bd7-45e1-ac08-2b5f3886a9bb

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Vendite' =
			
			VAR __ValueCurrentPeriod = [Vendite]
			VAR __ValuePreviousPeriod = [PQ Vendite]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth\Vendite
		lineageTag: 8fbfda3c-61b2-4c77-b8db-03dd877a4ddf

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Vendite' = ```
			
			DIVIDE ( 
			    [QOQ Vendite],
			    [PQ Vendite]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Vendite
		lineageTag: e3f09762-d0a3-475b-8ad5-dc82eb87b275

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Vendite' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\Growth\Vendite
		lineageTag: dc30cf0d-014f-423c-a211-e01dd94fd71b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Vendite' =
			
			VAR __ValueCurrentPeriod = [Vendite]
			VAR __ValuePreviousPeriod = [PM Vendite]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth\Vendite
		lineageTag: c9c7e96a-a1b4-4794-af21-81d01636e3b3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Vendite' = ```
			
			DIVIDE ( 
			    [MOM Vendite],
			    [PM Vendite]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Vendite
		lineageTag: b4cdd5ca-9805-49a3-975b-ccd26ce9825c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Vendite' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Vendite],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, YEAR ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\To-date growth\Vendite
		lineageTag: 0481ab12-660c-4c42-91c6-1076fb3f2ac6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Vendite' =
			
			VAR __ValueCurrentPeriod = [YTD Vendite]
			VAR __ValuePreviousPeriod = [PYTD Vendite]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\To-date growth\Vendite
		lineageTag: 0bd20092-a921-4ac6-a6f4-ff4502d1d339

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Vendite' = ```
			
			DIVIDE ( 
			    [YOYTD Vendite],
			    [PYTD Vendite]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Vendite
		lineageTag: b993776f-42f8-4d55-aa32-040547c41f29

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Vendite' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Vendite],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, QUARTER ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\To-date growth\Vendite
		lineageTag: fd8adecc-f5b2-4c80-b99c-be355241206e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Vendite' =
			
			VAR __ValueCurrentPeriod = [QTD Vendite]
			VAR __ValuePreviousPeriod = [PQTD Vendite]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\To-date growth\Vendite
		lineageTag: 4fa1c525-ba9e-4580-8fd2-2a2161385ebd

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Vendite' = ```
			
			DIVIDE ( 
			    [QOQTD Vendite],
			    [PQTD Vendite]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Vendite
		lineageTag: c0352f90-4042-4020-92f5-2974233a57ac

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Vendite' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Vendite],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\To-date growth\Vendite
		lineageTag: 86aeaa41-2e25-4bcd-80ac-6bde5536259c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Vendite' =
			
			VAR __ValueCurrentPeriod = [MTD Vendite]
			VAR __ValuePreviousPeriod = [PMTD Vendite]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\To-date growth\Vendite
		lineageTag: ba26d87a-b068-4dee-b4c7-a6c9bcd9e2ff

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Vendite' = ```
			
			DIVIDE ( 
			    [MOMTD Vendite],
			    [PMTD Vendite]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Vendite
		lineageTag: e8da3043-ea6d-4985-867c-914a88bc73c8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Vendite' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite],
			        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )
			    )
			)
		displayFolder: Time intelligence\Growth over full period\Vendite
		lineageTag: a61bf464-3142-4451-be2d-67fe44e534e7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Vendite' =
			
			VAR __ValueCurrentPeriod = [YTD Vendite]
			VAR __ValuePreviousPeriod = [PYC Vendite]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth over full period\Vendite
		lineageTag: 922f5f65-0279-474b-870e-ad8687712dcb

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Vendite' = ```
			
			DIVIDE ( 
			    [YTDOPY Vendite],
			    [PYC Vendite]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Vendite
		lineageTag: 180a3a90-80dc-4f85-b9e3-cc4644cfe3d3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Vendite' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite],
			        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )
			    )
			)
		displayFolder: Time intelligence\Growth over full period\Vendite
		lineageTag: 6f485623-0ca0-4281-b812-3d65880dd4bb

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Vendite' =
			
			VAR __ValueCurrentPeriod = [QTD Vendite]
			VAR __ValuePreviousPeriod = [PQC Vendite]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth over full period\Vendite
		lineageTag: 0ae41890-2318-4a3f-821b-ff3c25ed0a62

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Vendite' = ```
			
			DIVIDE ( 
			    [QTDOPQ Vendite],
			    [PQC Vendite]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Vendite
		lineageTag: d8a39b50-6bf2-4eef-94eb-14e4a462ce86

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Vendite' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite],
			        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )
			    )
			)
		displayFolder: Time intelligence\Growth over full period\Vendite
		lineageTag: 7499e516-0bff-41d1-a4e8-a45ef34a9f44

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Vendite' =
			
			VAR __ValueCurrentPeriod = [MTD Vendite]
			VAR __ValuePreviousPeriod = [PMC Vendite]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth over full period\Vendite
		lineageTag: e0f83339-99e5-486b-9757-a829364b8ca2

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Vendite' = ```
			
			DIVIDE ( 
			    [MTDOPM Vendite],
			    [PMC Vendite]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Vendite
		lineageTag: 4edd099e-5073-4779-957f-6f0e6ef9676a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Vendite' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite],
			        DATESINPERIOD (
			            'Date'[Date],
			            MAX ( 'Date'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		displayFolder: Time intelligence\Moving annual growth\Vendite
		lineageTag: f5ff8eee-6079-4e6f-8868-4c59f3d1fc92

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Vendite' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Vendite],
			        DATEADD ( 'Date'[Date], -1, YEAR )
			    )
			)
		displayFolder: Time intelligence\Moving annual growth\Vendite
		lineageTag: e5ce831c-2440-4bf8-9426-6bec18be83c4

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Vendite' =
			
			VAR __ValueCurrentPeriod = [MAT Vendite]
			VAR __ValuePreviousPeriod = [PYMAT Vendite]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Moving annual growth\Vendite
		lineageTag: 3fec3ca6-d3b8-4d5b-8f61-0d9406e7a4af

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Vendite' = ```
			
			DIVIDE ( 
			    [MATG Vendite],
			    [PYMAT Vendite]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Vendite
		lineageTag: ee2bcf8e-e07f-4588-8c87-0951b006914e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD Costo del venduto' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Costo del venduto],
			        DATESYTD ( 'Date'[Date] )
			    )
			)
		displayFolder: Time intelligence\To-date total\Costo del venduto
		lineageTag: 6cde6678-456e-456b-8c5f-2a77d32e1b3d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Costo del venduto' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Costo del venduto],
			        DATESQTD ( 'Date'[Date] )
			    )
			)
		displayFolder: Time intelligence\To-date total\Costo del venduto
		lineageTag: 7e988a2c-5c32-4b6c-983c-3acc74f330a0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Costo del venduto' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Costo del venduto],
			        DATESMTD ( 'Date'[Date] )
			    )
			)
		displayFolder: Time intelligence\To-date total\Costo del venduto
		lineageTag: 5e56bdbc-6650-4e01-ba8b-3c4cafe643f3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Costo del venduto' = ```
			
			
			    CALCULATE (
			        [Costo del venduto],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, YEAR ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			
			```
		displayFolder: Time intelligence\Growth\Costo del venduto
		lineageTag: 2498fed4-9b54-4e38-b2b9-8f9279f963fa

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YOY Costo del venduto' =
			
			VAR __ValueCurrentPeriod = [Costo del venduto]
			VAR __ValuePreviousPeriod = [PY Costo del venduto]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth\Costo del venduto
		lineageTag: cffab1f6-7e84-4faa-8d75-fe6ae7bfbdff

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Costo del venduto' = ```
			
			DIVIDE ( 
			    [YOY Costo del venduto],
			    [PY Costo del venduto]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Costo del venduto
		lineageTag: e4f75765-0641-4922-9fa1-c7205e2af319

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Costo del venduto' = ```
			
			
			    CALCULATE (
			        [Costo del venduto],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, QUARTER ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			
			```
		displayFolder: Time intelligence\Growth\Costo del venduto
		lineageTag: 635b7855-caeb-482f-bf7c-d86f978744b9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QOQ Costo del venduto' =
			
			VAR __ValueCurrentPeriod = [Costo del venduto]
			VAR __ValuePreviousPeriod = [PQ Costo del venduto]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth\Costo del venduto
		lineageTag: 3584e5f1-b6e9-427d-b819-e8009e693d2c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Costo del venduto' = ```
			
			DIVIDE ( 
			    [QOQ Costo del venduto],
			    [PQ Costo del venduto]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Costo del venduto
		lineageTag: 6b2c0e12-9577-48b1-86cb-82763239999b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Costo del venduto' = ```
			
			
			    CALCULATE (
			        [Costo del venduto],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			
			```
		displayFolder: Time intelligence\Growth\Costo del venduto
		lineageTag: ff8f17ad-18e7-4d63-b315-7dd0ee7a53d3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MOM Costo del venduto' =
			
			VAR __ValueCurrentPeriod = [Costo del venduto]
			VAR __ValuePreviousPeriod = [PM Costo del venduto]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth\Costo del venduto
		lineageTag: a711bfc3-3bb7-4fb5-b26d-bf369156eddb

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MOM % Costo del venduto' = ```
			
			DIVIDE ( 
			    [MOM Costo del venduto],
			    [PM Costo del venduto]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Costo del venduto
		lineageTag: e5daca30-8b13-46ad-8cc1-512aaa90a548

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Costo del venduto' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Costo del venduto],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, YEAR ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\To-date growth\Costo del venduto
		lineageTag: c502918c-057c-4778-a010-987d18296d76

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Costo del venduto' =
			
			VAR __ValueCurrentPeriod = [YTD Costo del venduto]
			VAR __ValuePreviousPeriod = [PYTD Costo del venduto]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\To-date growth\Costo del venduto
		lineageTag: c6b2b5b4-b1fe-430c-969e-43d8ceb79101

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Costo del venduto' = ```
			
			DIVIDE ( 
			    [YOYTD Costo del venduto],
			    [PYTD Costo del venduto]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Costo del venduto
		lineageTag: 0ffdc5da-a51f-4769-b0f2-a59188ad9188

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Costo del venduto' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Costo del venduto],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, QUARTER ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\To-date growth\Costo del venduto
		lineageTag: 4022b718-27cd-47c6-a1ad-9925eb8641d6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Costo del venduto' =
			
			VAR __ValueCurrentPeriod = [QTD Costo del venduto]
			VAR __ValuePreviousPeriod = [PQTD Costo del venduto]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\To-date growth\Costo del venduto
		lineageTag: 26d9f016-3323-43aa-bcef-36b69e295c13

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Costo del venduto' = ```
			
			DIVIDE ( 
			    [QOQTD Costo del venduto],
			    [PQTD Costo del venduto]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Costo del venduto
		lineageTag: 292a3d05-85d5-4a74-9bdd-97c6978eba01

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Costo del venduto' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Costo del venduto],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\To-date growth\Costo del venduto
		lineageTag: abc363eb-c717-451e-b164-94f0d7f2d8a7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Costo del venduto' =
			
			VAR __ValueCurrentPeriod = [MTD Costo del venduto]
			VAR __ValuePreviousPeriod = [PMTD Costo del venduto]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\To-date growth\Costo del venduto
		lineageTag: ffa2cd68-63d1-4890-ad10-8286e7f706d5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Costo del venduto' = ```
			
			DIVIDE ( 
			    [MOMTD Costo del venduto],
			    [PMTD Costo del venduto]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Costo del venduto
		lineageTag: fc612c79-4088-46a3-8d53-d5de3d3ad5e9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Costo del venduto' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Costo del venduto],
			        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )
			    )
			)
		displayFolder: Time intelligence\Growth over full period\Costo del venduto
		lineageTag: 81e6730e-d0f0-4d88-b8c4-7ad133236bec

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Costo del venduto' =
			
			VAR __ValueCurrentPeriod = [YTD Costo del venduto]
			VAR __ValuePreviousPeriod = [PYC Costo del venduto]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth over full period\Costo del venduto
		lineageTag: afe3d9dd-5f04-4b53-bea8-dd7699f06d25

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Costo del venduto' = ```
			
			DIVIDE ( 
			    [YTDOPY Costo del venduto],
			    [PYC Costo del venduto]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Costo del venduto
		lineageTag: eeb338c1-e593-4cf4-a50c-c1673fc34c17

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Costo del venduto' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Costo del venduto],
			        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )
			    )
			)
		displayFolder: Time intelligence\Growth over full period\Costo del venduto
		lineageTag: 24fd8a32-aadc-4e92-8352-3ba13a43ddd6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Costo del venduto' =
			
			VAR __ValueCurrentPeriod = [QTD Costo del venduto]
			VAR __ValuePreviousPeriod = [PQC Costo del venduto]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth over full period\Costo del venduto
		lineageTag: 09de02c4-dd6c-44ff-a4a4-fa7ea94e47c2

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Costo del venduto' = ```
			
			DIVIDE ( 
			    [QTDOPQ Costo del venduto],
			    [PQC Costo del venduto]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Costo del venduto
		lineageTag: 83675dc7-34ce-4bf0-9580-f056d35d18c2

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Costo del venduto' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Costo del venduto],
			        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )
			    )
			)
		displayFolder: Time intelligence\Growth over full period\Costo del venduto
		lineageTag: 4a5f6cb6-404f-4744-b923-92d53574dc3f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MTDOPM Costo del venduto' =
			
			VAR __ValueCurrentPeriod = [MTD Costo del venduto]
			VAR __ValuePreviousPeriod = [PMC Costo del venduto]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth over full period\Costo del venduto
		lineageTag: 66d76c53-3961-4334-9f9d-7ecaa6ee0748

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Costo del venduto' = ```
			
			DIVIDE ( 
			    [MTDOPM Costo del venduto],
			    [PMC Costo del venduto]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Costo del venduto
		lineageTag: 56ea163f-164d-4e85-9cf0-8ca97970ed9d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Costo del venduto' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Costo del venduto],
			        DATESINPERIOD (
			            'Date'[Date],
			            MAX ( 'Date'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		displayFolder: Time intelligence\Moving annual growth\Costo del venduto
		lineageTag: 1242d785-831f-4d12-b474-8bd566af278f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Costo del venduto' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Costo del venduto],
			        DATEADD ( 'Date'[Date], -1, YEAR )
			    )
			)
		displayFolder: Time intelligence\Moving annual growth\Costo del venduto
		lineageTag: 4fd1b5b9-9a51-4a5c-8a60-7e126e5031f6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Costo del venduto' =
			
			VAR __ValueCurrentPeriod = [MAT Costo del venduto]
			VAR __ValuePreviousPeriod = [PYMAT Costo del venduto]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Moving annual growth\Costo del venduto
		lineageTag: b33a1026-ad8a-485f-82a2-8a7525958491

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Costo del venduto' = ```
			
			DIVIDE ( 
			    [MATG Costo del venduto],
			    [PYMAT Costo del venduto]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Costo del venduto
		lineageTag: 86604e54-1b73-4799-8f12-36c7fe32a277

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD Margine' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine],
			        DATESYTD ( 'Date'[Date] )
			    )
			)
		displayFolder: Time intelligence\To-date total\Margine
		lineageTag: d769e113-d7b1-4f3c-ad23-52f948831f6a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Margine' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine],
			        DATESQTD ( 'Date'[Date] )
			    )
			)
		displayFolder: Time intelligence\To-date total\Margine
		lineageTag: 58345f4d-5fd5-45b9-8a8d-6464c3ef6f3a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Margine' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine],
			        DATESMTD ( 'Date'[Date] )
			    )
			)
		displayFolder: Time intelligence\To-date total\Margine
		lineageTag: ae9e6056-e653-4f8b-963b-f802adc51808

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Margine' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, YEAR ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\Growth\Margine
		lineageTag: 7e4e6304-b439-41c5-9185-6c50e0e6ebc1

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Margine' =
			
			VAR __ValueCurrentPeriod = [Margine]
			VAR __ValuePreviousPeriod = [PY Margine]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth\Margine
		lineageTag: d8964ebc-d3ee-49ac-be9a-02e164bc5776

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Margine' = ```
			
			DIVIDE ( 
			    [YOY Margine],
			    [PY Margine]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Margine
		lineageTag: e17ca744-af79-4310-96e2-57538f80ad4f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Margine' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, QUARTER ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\Growth\Margine
		lineageTag: 164dbd8c-a619-4e4c-bb77-3604ca5dcefa

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Margine' =
			
			VAR __ValueCurrentPeriod = [Margine]
			VAR __ValuePreviousPeriod = [PQ Margine]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth\Margine
		lineageTag: 46d50ab7-0c80-45fc-a186-4211a6dec015

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Margine' = ```
			
			DIVIDE ( 
			    [QOQ Margine],
			    [PQ Margine]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Margine
		lineageTag: c6384e17-56c7-4fdf-8ef5-083ef54791ff

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Margine' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\Growth\Margine
		lineageTag: 3c3c4b2d-daf6-4430-8295-fbf9e1db06a7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Margine' =
			
			VAR __ValueCurrentPeriod = [Margine]
			VAR __ValuePreviousPeriod = [PM Margine]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth\Margine
		lineageTag: 467de212-3aae-43c8-bbe5-5e0a79d6a814

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Margine' = ```
			
			DIVIDE ( 
			    [MOM Margine],
			    [PM Margine]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Margine
		lineageTag: b0c29a1b-46c3-4bff-86b0-b8e07662f006

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Margine' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Margine],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, YEAR ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\To-date growth\Margine
		lineageTag: 96ed27ed-8110-4de9-98e7-d4d5b2426159

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Margine' =
			
			VAR __ValueCurrentPeriod = [YTD Margine]
			VAR __ValuePreviousPeriod = [PYTD Margine]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\To-date growth\Margine
		lineageTag: 8d9faaad-2a11-454f-a37e-a76e540f028b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Margine' = ```
			
			DIVIDE ( 
			    [YOYTD Margine],
			    [PYTD Margine]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Margine
		lineageTag: 3c669528-1cbe-4812-bb9c-a7ac56cf26a5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Margine' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Margine],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, QUARTER ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\To-date growth\Margine
		lineageTag: 4c95a37c-5d54-44c1-9bc2-cf7e74c2164e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Margine' =
			
			VAR __ValueCurrentPeriod = [QTD Margine]
			VAR __ValuePreviousPeriod = [PQTD Margine]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\To-date growth\Margine
		lineageTag: 5c80c597-c663-4757-8ddd-34e9a9824863

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Margine' = ```
			
			DIVIDE ( 
			    [QOQTD Margine],
			    [PQTD Margine]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Margine
		lineageTag: 53f13137-03db-4994-8501-a12b6a45fec7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Margine' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Margine],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\To-date growth\Margine
		lineageTag: 9ea239f1-b5a2-41c9-972b-cb5663148fd0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Margine' =
			
			VAR __ValueCurrentPeriod = [MTD Margine]
			VAR __ValuePreviousPeriod = [PMTD Margine]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\To-date growth\Margine
		lineageTag: 210d472a-462d-456e-96f6-7b9da1ceaaa8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Margine' = ```
			
			DIVIDE ( 
			    [MOMTD Margine],
			    [PMTD Margine]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Margine
		lineageTag: 29c8ac3d-beb0-435e-9b4d-5dafed42b89a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Margine' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine],
			        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )
			    )
			)
		displayFolder: Time intelligence\Growth over full period\Margine
		lineageTag: 73863201-1c86-4873-b457-f67573f00146

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Margine' =
			
			VAR __ValueCurrentPeriod = [YTD Margine]
			VAR __ValuePreviousPeriod = [PYC Margine]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth over full period\Margine
		lineageTag: cab39650-2ac6-460c-bbd3-39d5388b96ed

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Margine' = ```
			
			DIVIDE ( 
			    [YTDOPY Margine],
			    [PYC Margine]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Margine
		lineageTag: 087b7f33-faff-498b-97df-c3673ea81b44

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Margine' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine],
			        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )
			    )
			)
		displayFolder: Time intelligence\Growth over full period\Margine
		lineageTag: 0ad86229-0737-4c93-a60e-cdf328397bca

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Margine' =
			
			VAR __ValueCurrentPeriod = [QTD Margine]
			VAR __ValuePreviousPeriod = [PQC Margine]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth over full period\Margine
		lineageTag: 475e099b-004a-48cb-aea2-2f897b18f611

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Margine' = ```
			
			DIVIDE ( 
			    [QTDOPQ Margine],
			    [PQC Margine]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Margine
		lineageTag: d54c890a-0e60-46bb-8759-16595c2b244a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Margine' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine],
			        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )
			    )
			)
		displayFolder: Time intelligence\Growth over full period\Margine
		lineageTag: e3fb42fe-03dc-4d69-a139-ae7a73cb9f34

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Margine' =
			
			VAR __ValueCurrentPeriod = [MTD Margine]
			VAR __ValuePreviousPeriod = [PMC Margine]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth over full period\Margine
		lineageTag: a2a13b79-3daf-484f-97cb-60d634810ba0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Margine' = ```
			
			DIVIDE ( 
			    [MTDOPM Margine],
			    [PMC Margine]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Margine
		lineageTag: f0a20104-7efd-4de6-9bc2-5b72187836c7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Margine' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine],
			        DATESINPERIOD (
			            'Date'[Date],
			            MAX ( 'Date'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		displayFolder: Time intelligence\Moving annual growth\Margine
		lineageTag: a99507fd-03d6-4ccc-a765-16aa2c196b5a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Margine' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Margine],
			        DATEADD ( 'Date'[Date], -1, YEAR )
			    )
			)
		displayFolder: Time intelligence\Moving annual growth\Margine
		lineageTag: 0209ecab-3313-476b-b307-8f41f29a873a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Margine' =
			
			VAR __ValueCurrentPeriod = [MAT Margine]
			VAR __ValuePreviousPeriod = [PYMAT Margine]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Moving annual growth\Margine
		lineageTag: 892894cd-5f2d-488a-8478-f95128f401f2

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Margine' = ```
			
			DIVIDE ( 
			    [MATG Margine],
			    [PYMAT Margine]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Margine
		lineageTag: 5514a337-a4f6-4446-83c8-9b8bfa48fb37

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD Margine %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine %],
			        DATESYTD ( 'Date'[Date] )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date total\Margine %
		lineageTag: 788515dc-40f3-4a39-9994-f26325bb3f71

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Margine %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine %],
			        DATESQTD ( 'Date'[Date] )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date total\Margine %
		lineageTag: 594b84a1-ece0-43ff-a03f-d43410c1beaf

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Margine %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine %],
			        DATESMTD ( 'Date'[Date] )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date total\Margine %
		lineageTag: 898dbf51-ebdc-4a4f-b7cb-a74cfc3c8ae9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Margine %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine %],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, YEAR ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Margine %
		lineageTag: dceac4fa-c414-4d53-9243-4c60e2ed095f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Margine %' =
			
			VAR __ValueCurrentPeriod = [Margine %]
			VAR __ValuePreviousPeriod = [PY Margine %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Margine %
		lineageTag: 877e22af-0524-428c-ab87-0a9d7a4aaea1

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Margine %' = ```
			
			DIVIDE ( 
			    [YOY Margine %],
			    [PY Margine %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Margine %
		lineageTag: f77948a4-8bd3-4d39-8060-69d1b977cd7f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Margine %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine %],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, QUARTER ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Margine %
		lineageTag: 51e5f19f-778f-49db-b614-5fa6a0fa783c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Margine %' =
			
			VAR __ValueCurrentPeriod = [Margine %]
			VAR __ValuePreviousPeriod = [PQ Margine %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Margine %
		lineageTag: ff6ef407-11aa-4b44-80b5-e522c57ee535

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Margine %' = ```
			
			DIVIDE ( 
			    [QOQ Margine %],
			    [PQ Margine %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Margine %
		lineageTag: cd2bfbb5-ecf9-4468-bedb-1772ce36aace

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Margine %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine %],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Margine %
		lineageTag: 634e89fb-11bb-466a-b465-3f35309cf56d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Margine %' =
			
			VAR __ValueCurrentPeriod = [Margine %]
			VAR __ValuePreviousPeriod = [PM Margine %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Margine %
		lineageTag: b421f84c-5cf8-4c5d-94e1-9e2c0362f20a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Margine %' = ```
			
			DIVIDE ( 
			    [MOM Margine %],
			    [PM Margine %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Margine %
		lineageTag: 05a940e7-2c0f-47aa-8dfc-e7fc9cc7e3f1

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Margine %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Margine %],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, YEAR ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Margine %
		lineageTag: 2deb2d82-8888-4717-a3ec-e164f6e080b4

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Margine %' =
			
			VAR __ValueCurrentPeriod = [YTD Margine %]
			VAR __ValuePreviousPeriod = [PYTD Margine %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Margine %
		lineageTag: d6d482af-df35-410c-a74a-8ae051607ac5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Margine %' = ```
			
			DIVIDE ( 
			    [YOYTD Margine %],
			    [PYTD Margine %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Margine %
		lineageTag: b4e15229-6384-43fd-908e-e9551299894b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Margine %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Margine %],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, QUARTER ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Margine %
		lineageTag: 6acf35da-7c73-4204-85e7-3db4cc4f407b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Margine %' =
			
			VAR __ValueCurrentPeriod = [QTD Margine %]
			VAR __ValuePreviousPeriod = [PQTD Margine %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Margine %
		lineageTag: 1a824801-59f6-434c-abbf-04e241741fa1

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Margine %' = ```
			
			DIVIDE ( 
			    [QOQTD Margine %],
			    [PQTD Margine %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Margine %
		lineageTag: 921809b6-355a-4059-aa10-507f9e91c983

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Margine %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Margine %],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Margine %
		lineageTag: 6fc79380-c493-4ab2-ac51-cca459536804

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Margine %' =
			
			VAR __ValueCurrentPeriod = [MTD Margine %]
			VAR __ValuePreviousPeriod = [PMTD Margine %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Margine %
		lineageTag: f950f491-09cf-49d6-9a9f-c387fc96d9cb

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Margine %' = ```
			
			DIVIDE ( 
			    [MOMTD Margine %],
			    [PMTD Margine %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Margine %
		lineageTag: 42f5e138-d296-43f1-b23e-67338a459c30

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Margine %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine %],
			        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Margine %
		lineageTag: 0db41079-9bd1-4f8d-8d9b-63cab3298c7e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Margine %' =
			
			VAR __ValueCurrentPeriod = [YTD Margine %]
			VAR __ValuePreviousPeriod = [PYC Margine %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Margine %
		lineageTag: 01cf287a-d644-4d39-aad9-a63fc8f07516

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Margine %' = ```
			
			DIVIDE ( 
			    [YTDOPY Margine %],
			    [PYC Margine %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Margine %
		lineageTag: 35e42915-8093-469b-8c9c-6164e80af958

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Margine %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine %],
			        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Margine %
		lineageTag: 714bbcf2-3184-4a12-b5f7-fa3be054b27e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Margine %' =
			
			VAR __ValueCurrentPeriod = [QTD Margine %]
			VAR __ValuePreviousPeriod = [PQC Margine %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Margine %
		lineageTag: f2cd7062-884c-4ef9-a262-68e2ce3beb17

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Margine %' = ```
			
			DIVIDE ( 
			    [QTDOPQ Margine %],
			    [PQC Margine %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Margine %
		lineageTag: 691dc1e4-ab03-4bd5-84c5-46b973e3ac82

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Margine %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine %],
			        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Margine %
		lineageTag: a8c99daf-db58-4e2c-916c-cbdf7ebeefad

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Margine %' =
			
			VAR __ValueCurrentPeriod = [MTD Margine %]
			VAR __ValuePreviousPeriod = [PMC Margine %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Margine %
		lineageTag: 92999913-ac2f-4ca8-8a29-7fcea569662e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Margine %' = ```
			
			DIVIDE ( 
			    [MTDOPM Margine %],
			    [PMC Margine %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Margine %
		lineageTag: 3217c1c5-c8f0-49fc-a80a-7c85474255a6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Margine %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Margine %],
			        DATESINPERIOD (
			            'Date'[Date],
			            MAX ( 'Date'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Moving annual growth\Margine %
		lineageTag: f48a6f5c-1d36-4ef4-8f6b-d2f1fb7121c2

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Margine %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Margine %],
			        DATEADD ( 'Date'[Date], -1, YEAR )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Moving annual growth\Margine %
		lineageTag: efec06eb-72fb-45bb-b8a2-c97c0f1deb56

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Margine %' =
			
			VAR __ValueCurrentPeriod = [MAT Margine %]
			VAR __ValuePreviousPeriod = [PYMAT Margine %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Moving annual growth\Margine %
		lineageTag: 0e68dd9b-749d-48cf-84f9-67de75dc0740

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Margine %' = ```
			
			DIVIDE ( 
			    [MATG Margine %],
			    [PYMAT Margine %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Margine %
		lineageTag: 892dc8c5-cfa0-49a0-b4bd-cf3c46ed54f3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD Vendite Anno precedente' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite Anno precedente],
			        DATESYTD ( 'Date'[Date] )
			    )
			)
		displayFolder: Time intelligence\To-date total\Vendite Anno precedente
		lineageTag: 737f3804-cf4e-4897-84d1-3d1061973dcf

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Vendite Anno precedente' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite Anno precedente],
			        DATESQTD ( 'Date'[Date] )
			    )
			)
		displayFolder: Time intelligence\To-date total\Vendite Anno precedente
		lineageTag: 1d17cfd3-a330-4150-948a-34c1e3885558

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Vendite Anno precedente' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite Anno precedente],
			        DATESMTD ( 'Date'[Date] )
			    )
			)
		displayFolder: Time intelligence\To-date total\Vendite Anno precedente
		lineageTag: fbb7f81e-f508-4e18-9d1b-d0382967840e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Vendite Anno precedente' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite Anno precedente],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, YEAR ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\Growth\Vendite Anno precedente
		lineageTag: c6b902f6-e3e6-4774-b09c-b9cd38963ba9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Vendite Anno precedente' =
			
			VAR __ValueCurrentPeriod = [Vendite Anno precedente]
			VAR __ValuePreviousPeriod = [PY Vendite Anno precedente]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth\Vendite Anno precedente
		lineageTag: 03735f72-1bc9-4da9-a692-323d9a4f6d5e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Vendite Anno precedente' = ```
			
			DIVIDE ( 
			    [YOY Vendite Anno precedente],
			    [PY Vendite Anno precedente]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Vendite Anno precedente
		lineageTag: c4643955-1122-4fe7-bb9b-21aebfa5b60c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Vendite Anno precedente' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite Anno precedente],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, QUARTER ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\Growth\Vendite Anno precedente
		lineageTag: ac5e9f5f-8667-4b39-bfe8-831981867781

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Vendite Anno precedente' =
			
			VAR __ValueCurrentPeriod = [Vendite Anno precedente]
			VAR __ValuePreviousPeriod = [PQ Vendite Anno precedente]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth\Vendite Anno precedente
		lineageTag: 8bfe4615-b8f3-4606-ad75-494864625286

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Vendite Anno precedente' = ```
			
			DIVIDE ( 
			    [QOQ Vendite Anno precedente],
			    [PQ Vendite Anno precedente]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Vendite Anno precedente
		lineageTag: 123fa473-3f32-4c78-b97e-3f47af4ccb78

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Vendite Anno precedente' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite Anno precedente],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\Growth\Vendite Anno precedente
		lineageTag: 2a0eb36c-367b-4c91-a966-f608b79cef49

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Vendite Anno precedente' =
			
			VAR __ValueCurrentPeriod = [Vendite Anno precedente]
			VAR __ValuePreviousPeriod = [PM Vendite Anno precedente]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth\Vendite Anno precedente
		lineageTag: 6f49e924-1c52-44b9-a930-ac02e000c31b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Vendite Anno precedente' = ```
			
			DIVIDE ( 
			    [MOM Vendite Anno precedente],
			    [PM Vendite Anno precedente]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Vendite Anno precedente
		lineageTag: 7884a25e-3af9-4f66-9647-d54bdcf14968

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Vendite Anno precedente' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Vendite Anno precedente],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, YEAR ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\To-date growth\Vendite Anno precedente
		lineageTag: d34be094-e0b6-4030-88d3-3025c2660c9a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Vendite Anno precedente' =
			
			VAR __ValueCurrentPeriod = [YTD Vendite Anno precedente]
			VAR __ValuePreviousPeriod = [PYTD Vendite Anno precedente]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\To-date growth\Vendite Anno precedente
		lineageTag: 3c172920-8790-4c4e-99f4-5b7e996ed629

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Vendite Anno precedente' = ```
			
			DIVIDE ( 
			    [YOYTD Vendite Anno precedente],
			    [PYTD Vendite Anno precedente]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Vendite Anno precedente
		lineageTag: 98dd146d-850e-450d-ad40-60012f6b3f93

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Vendite Anno precedente' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Vendite Anno precedente],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, QUARTER ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\To-date growth\Vendite Anno precedente
		lineageTag: 454bdd65-f6df-4329-8423-b368d2c04c20

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Vendite Anno precedente' =
			
			VAR __ValueCurrentPeriod = [QTD Vendite Anno precedente]
			VAR __ValuePreviousPeriod = [PQTD Vendite Anno precedente]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\To-date growth\Vendite Anno precedente
		lineageTag: bf08782d-f585-413b-9fe0-acb864f51c89

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Vendite Anno precedente' = ```
			
			DIVIDE ( 
			    [QOQTD Vendite Anno precedente],
			    [PQTD Vendite Anno precedente]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Vendite Anno precedente
		lineageTag: 29e9b180-6070-4a35-a70e-afe46621c3e5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Vendite Anno precedente' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Vendite Anno precedente],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		displayFolder: Time intelligence\To-date growth\Vendite Anno precedente
		lineageTag: 0be3c73d-73c2-48f4-8e72-3a269432d953

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Vendite Anno precedente' =
			
			VAR __ValueCurrentPeriod = [MTD Vendite Anno precedente]
			VAR __ValuePreviousPeriod = [PMTD Vendite Anno precedente]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\To-date growth\Vendite Anno precedente
		lineageTag: ee15c417-e151-4a0f-988b-062894499a23

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Vendite Anno precedente' = ```
			
			DIVIDE ( 
			    [MOMTD Vendite Anno precedente],
			    [PMTD Vendite Anno precedente]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Vendite Anno precedente
		lineageTag: 892f5a95-ae2b-4b55-9284-1bc8dff60946

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Vendite Anno precedente' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite Anno precedente],
			        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )
			    )
			)
		displayFolder: Time intelligence\Growth over full period\Vendite Anno precedente
		lineageTag: 4cd3a126-4fed-4447-952b-55fd75df0cf0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Vendite Anno precedente' =
			
			VAR __ValueCurrentPeriod = [YTD Vendite Anno precedente]
			VAR __ValuePreviousPeriod = [PYC Vendite Anno precedente]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth over full period\Vendite Anno precedente
		lineageTag: 5191e4e7-7283-4251-a541-09a13e8a988f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Vendite Anno precedente' = ```
			
			DIVIDE ( 
			    [YTDOPY Vendite Anno precedente],
			    [PYC Vendite Anno precedente]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Vendite Anno precedente
		lineageTag: 75461f77-ceb0-419d-9613-3768b83412e1

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Vendite Anno precedente' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite Anno precedente],
			        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )
			    )
			)
		displayFolder: Time intelligence\Growth over full period\Vendite Anno precedente
		lineageTag: ad68078c-fe9e-4f9b-a729-cdc070d67f60

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Vendite Anno precedente' =
			
			VAR __ValueCurrentPeriod = [QTD Vendite Anno precedente]
			VAR __ValuePreviousPeriod = [PQC Vendite Anno precedente]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth over full period\Vendite Anno precedente
		lineageTag: ed80200c-df55-4732-ba29-a8d186d7cc06

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Vendite Anno precedente' = ```
			
			DIVIDE ( 
			    [QTDOPQ Vendite Anno precedente],
			    [PQC Vendite Anno precedente]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Vendite Anno precedente
		lineageTag: 7ac92ca3-2bdd-4e06-ae47-84a8b340ac76

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Vendite Anno precedente' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite Anno precedente],
			        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )
			    )
			)
		displayFolder: Time intelligence\Growth over full period\Vendite Anno precedente
		lineageTag: 48152099-cecf-499c-be79-dbbae44f2a73

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Vendite Anno precedente' =
			
			VAR __ValueCurrentPeriod = [MTD Vendite Anno precedente]
			VAR __ValuePreviousPeriod = [PMC Vendite Anno precedente]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Growth over full period\Vendite Anno precedente
		lineageTag: 966f8d1b-4990-422d-b49e-db0ce562f508

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Vendite Anno precedente' = ```
			
			DIVIDE ( 
			    [MTDOPM Vendite Anno precedente],
			    [PMC Vendite Anno precedente]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Vendite Anno precedente
		lineageTag: 687937fb-8a9e-4e54-b1d3-067d8c1dba6a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Vendite Anno precedente' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite Anno precedente],
			        DATESINPERIOD (
			            'Date'[Date],
			            MAX ( 'Date'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		displayFolder: Time intelligence\Moving annual growth\Vendite Anno precedente
		lineageTag: 7ca8c639-4298-4f91-9b2a-6b05550e4016

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Vendite Anno precedente' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Vendite Anno precedente],
			        DATEADD ( 'Date'[Date], -1, YEAR )
			    )
			)
		displayFolder: Time intelligence\Moving annual growth\Vendite Anno precedente
		lineageTag: 838cf197-9153-4ade-94c1-544accaea3c6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Vendite Anno precedente' =
			
			VAR __ValueCurrentPeriod = [MAT Vendite Anno precedente]
			VAR __ValuePreviousPeriod = [PYMAT Vendite Anno precedente]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		displayFolder: Time intelligence\Moving annual growth\Vendite Anno precedente
		lineageTag: 8a328176-80d5-41c6-af23-589f212ba1d7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Vendite Anno precedente' = ```
			
			DIVIDE ( 
			    [MATG Vendite Anno precedente],
			    [PYMAT Vendite Anno precedente]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Vendite Anno precedente
		lineageTag: 06bc0277-326a-4e16-a463-9cb81488454d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD Vendite YoY %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite YoY %],
			        DATESYTD ( 'Date'[Date] )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date total\Vendite YoY %
		lineageTag: 01b3339c-7176-4932-8e8f-fa62cf867b7c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Vendite YoY %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite YoY %],
			        DATESQTD ( 'Date'[Date] )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date total\Vendite YoY %
		lineageTag: 72c9ef2e-a504-4a18-aa83-1190215c40bf

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Vendite YoY %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite YoY %],
			        DATESMTD ( 'Date'[Date] )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date total\Vendite YoY %
		lineageTag: bdca2769-cd8b-4aea-a539-38993fc622fc

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Vendite YoY %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite YoY %],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, YEAR ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Vendite YoY %
		lineageTag: 2f8d8bb3-4619-429a-afde-aa392551b334

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Vendite YoY %' =
			
			VAR __ValueCurrentPeriod = [Vendite YoY %]
			VAR __ValuePreviousPeriod = [PY Vendite YoY %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Vendite YoY %
		lineageTag: 115f1752-8b01-43ee-9614-7a9e30f033d1

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Vendite YoY %' = ```
			
			DIVIDE ( 
			    [YOY Vendite YoY %],
			    [PY Vendite YoY %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Vendite YoY %
		lineageTag: 8ea519a1-a888-4e75-bb00-7bda9c6c8289

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Vendite YoY %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite YoY %],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, QUARTER ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Vendite YoY %
		lineageTag: 357fc8af-f7ec-41a6-b5a6-b82955c28364

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Vendite YoY %' =
			
			VAR __ValueCurrentPeriod = [Vendite YoY %]
			VAR __ValuePreviousPeriod = [PQ Vendite YoY %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Vendite YoY %
		lineageTag: 3d0df344-df3b-4cb8-a16e-19140156a59f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Vendite YoY %' = ```
			
			DIVIDE ( 
			    [QOQ Vendite YoY %],
			    [PQ Vendite YoY %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Vendite YoY %
		lineageTag: 4781ce6c-1451-487f-a88f-9eb59465e452

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Vendite YoY %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite YoY %],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Vendite YoY %
		lineageTag: 4ffd7b27-3f3f-4461-8d6d-390418160ab7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Vendite YoY %' =
			
			VAR __ValueCurrentPeriod = [Vendite YoY %]
			VAR __ValuePreviousPeriod = [PM Vendite YoY %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth\Vendite YoY %
		lineageTag: b4f48374-3d4e-4d3f-a87b-c5bf1831adf5

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Vendite YoY %' = ```
			
			DIVIDE ( 
			    [MOM Vendite YoY %],
			    [PM Vendite YoY %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Vendite YoY %
		lineageTag: be6cd9c9-88f0-48d1-ab80-ddfc2b70c4ed

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Vendite YoY %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Vendite YoY %],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, YEAR ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Vendite YoY %
		lineageTag: 3d5586ae-9674-488d-9a97-2d2c61887d29

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Vendite YoY %' =
			
			VAR __ValueCurrentPeriod = [YTD Vendite YoY %]
			VAR __ValuePreviousPeriod = [PYTD Vendite YoY %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Vendite YoY %
		lineageTag: 64951565-d109-491a-b044-2446104ce824

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Vendite YoY %' = ```
			
			DIVIDE ( 
			    [YOYTD Vendite YoY %],
			    [PYTD Vendite YoY %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Vendite YoY %
		lineageTag: 5bb0bd31-de6b-4d0b-8f34-526bcdfe563a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Vendite YoY %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Vendite YoY %],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, QUARTER ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Vendite YoY %
		lineageTag: b3797c49-241a-4d30-a870-ce4545ae17f3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Vendite YoY %' =
			
			VAR __ValueCurrentPeriod = [QTD Vendite YoY %]
			VAR __ValuePreviousPeriod = [PQTD Vendite YoY %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Vendite YoY %
		lineageTag: 85a90cd4-082c-4bd2-a3f3-6eedeebeeb60

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Vendite YoY %' = ```
			
			DIVIDE ( 
			    [QOQTD Vendite YoY %],
			    [PQTD Vendite YoY %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Vendite YoY %
		lineageTag: f0c3f071-ea8e-4ec6-b946-a5391d4d25a0

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Vendite YoY %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Vendite YoY %],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Vendite YoY %
		lineageTag: be921c38-badc-4a59-965e-c86af5cc18d7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Vendite YoY %' =
			
			VAR __ValueCurrentPeriod = [MTD Vendite YoY %]
			VAR __ValuePreviousPeriod = [PMTD Vendite YoY %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\To-date growth\Vendite YoY %
		lineageTag: 47f15380-4c5b-442f-b690-506c7610a4ef

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Vendite YoY %' = ```
			
			DIVIDE ( 
			    [MOMTD Vendite YoY %],
			    [PMTD Vendite YoY %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Vendite YoY %
		lineageTag: ead92fad-5572-4130-a019-1f0638e51eca

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Vendite YoY %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite YoY %],
			        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Vendite YoY %
		lineageTag: f6a7169b-55e5-4159-99f4-16045ccb3390

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Vendite YoY %' =
			
			VAR __ValueCurrentPeriod = [YTD Vendite YoY %]
			VAR __ValuePreviousPeriod = [PYC Vendite YoY %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Vendite YoY %
		lineageTag: 60de2d94-1693-458c-9097-dd4e01b5dfc2

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Vendite YoY %' = ```
			
			DIVIDE ( 
			    [YTDOPY Vendite YoY %],
			    [PYC Vendite YoY %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Vendite YoY %
		lineageTag: 1e849b8a-dc57-411f-ba47-26f93a885495

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Vendite YoY %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite YoY %],
			        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Vendite YoY %
		lineageTag: 421d5a09-cc9d-4c08-9427-801ca4fc5f90

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Vendite YoY %' =
			
			VAR __ValueCurrentPeriod = [QTD Vendite YoY %]
			VAR __ValuePreviousPeriod = [PQC Vendite YoY %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Vendite YoY %
		lineageTag: c99434c3-d975-4272-8f82-df9f30b8a3ad

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Vendite YoY %' = ```
			
			DIVIDE ( 
			    [QTDOPQ Vendite YoY %],
			    [PQC Vendite YoY %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Vendite YoY %
		lineageTag: 29b5aa92-4898-4b84-b10f-2daa09b862ab

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Vendite YoY %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite YoY %],
			        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Vendite YoY %
		lineageTag: 308c5b8c-60b2-4ac6-9d3a-75698ffa3099

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Vendite YoY %' =
			
			VAR __ValueCurrentPeriod = [MTD Vendite YoY %]
			VAR __ValuePreviousPeriod = [PMC Vendite YoY %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Growth over full period\Vendite YoY %
		lineageTag: de7b1c82-bee5-460d-a44c-28eb0b25ec1f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Vendite YoY %' = ```
			
			DIVIDE ( 
			    [MTDOPM Vendite YoY %],
			    [PMC Vendite YoY %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Vendite YoY %
		lineageTag: b12f4417-d77b-4d60-a1fe-b8e1638274aa

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Vendite YoY %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Vendite YoY %],
			        DATESINPERIOD (
			            'Date'[Date],
			            MAX ( 'Date'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Moving annual growth\Vendite YoY %
		lineageTag: 7354a1f8-cfea-466f-b830-ddc9919684ac

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Vendite YoY %' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Vendite YoY %],
			        DATEADD ( 'Date'[Date], -1, YEAR )
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Moving annual growth\Vendite YoY %
		lineageTag: 2b6cebf0-c905-4dba-a6c2-6be3fc35ef7c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Vendite YoY %' =
			
			VAR __ValueCurrentPeriod = [MAT Vendite YoY %]
			VAR __ValuePreviousPeriod = [PYMAT Vendite YoY %]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time intelligence\Moving annual growth\Vendite YoY %
		lineageTag: 5fe01754-a6c0-4932-be76-d2dbf6c52cf8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Vendite YoY %' = ```
			
			DIVIDE ( 
			    [MATG Vendite YoY %],
			    [PYMAT Vendite YoY %]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Vendite YoY %
		lineageTag: b6036d57-9c6c-448d-8865-4108a8a5ae3e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD Lotti in scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in scadenza 30gg],
			        DATESYTD ( 'Date'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Lotti in scadenza 30gg
		lineageTag: a7962aaa-0670-4484-b0e9-299ac302450f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Lotti in scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in scadenza 30gg],
			        DATESQTD ( 'Date'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Lotti in scadenza 30gg
		lineageTag: ab808080-d27a-4e22-9645-dd322d9a05d2

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Lotti in scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in scadenza 30gg],
			        DATESMTD ( 'Date'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Lotti in scadenza 30gg
		lineageTag: a342523a-2ece-4e64-b42b-6dbd39564744

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Lotti in scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in scadenza 30gg],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, YEAR ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Lotti in scadenza 30gg
		lineageTag: a1388868-23eb-4545-ac5d-a7b51572d8a6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Lotti in scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [Lotti in scadenza 30gg]
			VAR __ValuePreviousPeriod = [PY Lotti in scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Lotti in scadenza 30gg
		lineageTag: 8503331e-3cec-44a1-8580-999505a2178e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Lotti in scadenza 30gg' = ```
			
			DIVIDE ( 
			    [YOY Lotti in scadenza 30gg],
			    [PY Lotti in scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Lotti in scadenza 30gg
		lineageTag: 39f3625e-4f0e-4826-be4d-67cde0bfe3de

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Lotti in scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in scadenza 30gg],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, QUARTER ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Lotti in scadenza 30gg
		lineageTag: 63018821-e154-4340-99ff-07023fa4d96c

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Lotti in scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [Lotti in scadenza 30gg]
			VAR __ValuePreviousPeriod = [PQ Lotti in scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Lotti in scadenza 30gg
		lineageTag: 3f2597b5-08b5-4e56-8abe-1f7acf98d113

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Lotti in scadenza 30gg' = ```
			
			DIVIDE ( 
			    [QOQ Lotti in scadenza 30gg],
			    [PQ Lotti in scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Lotti in scadenza 30gg
		lineageTag: fdd18ffc-9340-41a4-ab1e-71b537b27b84

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Lotti in scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in scadenza 30gg],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Lotti in scadenza 30gg
		lineageTag: 1b2f998e-e1cb-4680-ac3c-4aea8e9cb4bd

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Lotti in scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [Lotti in scadenza 30gg]
			VAR __ValuePreviousPeriod = [PM Lotti in scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Lotti in scadenza 30gg
		lineageTag: 5d9c60b8-32ce-4840-a8b8-c98720971f1f

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Lotti in scadenza 30gg' = ```
			
			DIVIDE ( 
			    [MOM Lotti in scadenza 30gg],
			    [PM Lotti in scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Lotti in scadenza 30gg
		lineageTag: 47edd4f0-b978-4e85-bf85-6a4b3fc352d6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Lotti in scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Lotti in scadenza 30gg],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, YEAR ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Lotti in scadenza 30gg
		lineageTag: cce22540-24ba-4338-ab02-247aa490a6e1

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Lotti in scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [YTD Lotti in scadenza 30gg]
			VAR __ValuePreviousPeriod = [PYTD Lotti in scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Lotti in scadenza 30gg
		lineageTag: 716ef7cc-ee0f-4c45-a0c0-78e66636f6e8

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Lotti in scadenza 30gg' = ```
			
			DIVIDE ( 
			    [YOYTD Lotti in scadenza 30gg],
			    [PYTD Lotti in scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Lotti in scadenza 30gg
		lineageTag: bc641b75-a2fd-4877-87ae-f2f1b2e82152

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Lotti in scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Lotti in scadenza 30gg],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, QUARTER ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Lotti in scadenza 30gg
		lineageTag: 5064fddb-1d94-47d1-b1c5-acf5e6be89c3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Lotti in scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [QTD Lotti in scadenza 30gg]
			VAR __ValuePreviousPeriod = [PQTD Lotti in scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Lotti in scadenza 30gg
		lineageTag: 29408e4d-37da-404a-9a8f-87d6872d2e5d

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Lotti in scadenza 30gg' = ```
			
			DIVIDE ( 
			    [QOQTD Lotti in scadenza 30gg],
			    [PQTD Lotti in scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Lotti in scadenza 30gg
		lineageTag: b8be26a7-f47f-4870-96b4-51d8d6ca7b96

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Lotti in scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Lotti in scadenza 30gg],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Lotti in scadenza 30gg
		lineageTag: 490d5d6d-d3b0-41e6-acb4-5d1bc65cc6c7

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Lotti in scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [MTD Lotti in scadenza 30gg]
			VAR __ValuePreviousPeriod = [PMTD Lotti in scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Lotti in scadenza 30gg
		lineageTag: d9c791c5-39c7-415a-a2ce-7b56c2029d51

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Lotti in scadenza 30gg' = ```
			
			DIVIDE ( 
			    [MOMTD Lotti in scadenza 30gg],
			    [PMTD Lotti in scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Lotti in scadenza 30gg
		lineageTag: 8a35519c-6dca-415a-a3bb-f8d1c4441411

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Lotti in scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in scadenza 30gg],
			        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Lotti in scadenza 30gg
		lineageTag: 56924dce-7869-4a19-bb37-3c61e246c664

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Lotti in scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [YTD Lotti in scadenza 30gg]
			VAR __ValuePreviousPeriod = [PYC Lotti in scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Lotti in scadenza 30gg
		lineageTag: ce06b962-2063-4d63-8b16-ae69c46eb863

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Lotti in scadenza 30gg' = ```
			
			DIVIDE ( 
			    [YTDOPY Lotti in scadenza 30gg],
			    [PYC Lotti in scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Lotti in scadenza 30gg
		lineageTag: 5c8d37ad-93a5-43da-973c-0a3c72bf0b85

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Lotti in scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in scadenza 30gg],
			        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Lotti in scadenza 30gg
		lineageTag: c827bc55-892a-4093-84c6-5190fd98913b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Lotti in scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [QTD Lotti in scadenza 30gg]
			VAR __ValuePreviousPeriod = [PQC Lotti in scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Lotti in scadenza 30gg
		lineageTag: f652ecdc-894d-48cf-bf57-7d697f85ff03

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Lotti in scadenza 30gg' = ```
			
			DIVIDE ( 
			    [QTDOPQ Lotti in scadenza 30gg],
			    [PQC Lotti in scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Lotti in scadenza 30gg
		lineageTag: d637a4b5-53c4-4941-b5a7-c3a5e94555fb

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Lotti in scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in scadenza 30gg],
			        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Lotti in scadenza 30gg
		lineageTag: d479ca00-2990-4346-8b84-60889bfd7edf

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Lotti in scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [MTD Lotti in scadenza 30gg]
			VAR __ValuePreviousPeriod = [PMC Lotti in scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Lotti in scadenza 30gg
		lineageTag: 4252055f-0f1b-45ea-af9a-035e8fbe14ee

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Lotti in scadenza 30gg' = ```
			
			DIVIDE ( 
			    [MTDOPM Lotti in scadenza 30gg],
			    [PMC Lotti in scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Lotti in scadenza 30gg
		lineageTag: 41163ae6-c0e3-4714-aec1-3c16fa692630

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Lotti in scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in scadenza 30gg],
			        DATESINPERIOD (
			            'Date'[Date],
			            MAX ( 'Date'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Lotti in scadenza 30gg
		lineageTag: 252f26d3-5932-4f90-ae02-75e52c22c792

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Lotti in scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Lotti in scadenza 30gg],
			        DATEADD ( 'Date'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Lotti in scadenza 30gg
		lineageTag: 8d937dbb-e515-42ff-8ad7-8c5be08e607e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Lotti in scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [MAT Lotti in scadenza 30gg]
			VAR __ValuePreviousPeriod = [PYMAT Lotti in scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Lotti in scadenza 30gg
		lineageTag: 69ed8282-5a71-4063-ab9d-486eb052f547

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Lotti in scadenza 30gg' = ```
			
			DIVIDE ( 
			    [MATG Lotti in scadenza 30gg],
			    [PYMAT Lotti in scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Lotti in scadenza 30gg
		lineageTag: d393c52a-8ba3-463c-8d29-ba9b921588cb

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTD Lotti in magazzino scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in magazzino scadenza 30gg],
			        DATESYTD ( 'Date'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Lotti in magazzino scadenza 30gg
		lineageTag: 695d9a47-24ab-4fef-accb-3680c5fa6ca9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTD Lotti in magazzino scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in magazzino scadenza 30gg],
			        DATESQTD ( 'Date'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Lotti in magazzino scadenza 30gg
		lineageTag: bab1433b-0eaa-4396-bc0f-6f1bf48e8599

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTD Lotti in magazzino scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in magazzino scadenza 30gg],
			        DATESMTD ( 'Date'[Date] )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date total\Lotti in magazzino scadenza 30gg
		lineageTag: 3e8f8fba-a276-4655-95ad-27295bc783d3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PY Lotti in magazzino scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in magazzino scadenza 30gg],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, YEAR ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Lotti in magazzino scadenza 30gg
		lineageTag: f15f6435-e36f-4c1a-ae30-0146679e2771

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY Lotti in magazzino scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [Lotti in magazzino scadenza 30gg]
			VAR __ValuePreviousPeriod = [PY Lotti in magazzino scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Lotti in magazzino scadenza 30gg
		lineageTag: f4012bd7-c42e-4d38-8bd8-d85e420dcab2

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOY % Lotti in magazzino scadenza 30gg' = ```
			
			DIVIDE ( 
			    [YOY Lotti in magazzino scadenza 30gg],
			    [PY Lotti in magazzino scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Lotti in magazzino scadenza 30gg
		lineageTag: 2ba124f3-598d-4cac-923d-d44be885490e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQ Lotti in magazzino scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in magazzino scadenza 30gg],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, QUARTER ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Lotti in magazzino scadenza 30gg
		lineageTag: 58707090-abc1-4b9a-9369-6f734850d650

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ Lotti in magazzino scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [Lotti in magazzino scadenza 30gg]
			VAR __ValuePreviousPeriod = [PQ Lotti in magazzino scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Lotti in magazzino scadenza 30gg
		lineageTag: 0e19ccac-5594-4355-a2e8-2d593a076978

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQ % Lotti in magazzino scadenza 30gg' = ```
			
			DIVIDE ( 
			    [QOQ Lotti in magazzino scadenza 30gg],
			    [PQ Lotti in magazzino scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Lotti in magazzino scadenza 30gg
		lineageTag: 06568322-92f7-4374-bc08-ff1b09954239

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PM Lotti in magazzino scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in magazzino scadenza 30gg],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth\Lotti in magazzino scadenza 30gg
		lineageTag: c5ec2d51-4758-4f39-941f-56d4678548e4

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM Lotti in magazzino scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [Lotti in magazzino scadenza 30gg]
			VAR __ValuePreviousPeriod = [PM Lotti in magazzino scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth\Lotti in magazzino scadenza 30gg
		lineageTag: e1dc8ab3-116c-4af1-bebc-5f7f68dd6ef9

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOM % Lotti in magazzino scadenza 30gg' = ```
			
			DIVIDE ( 
			    [MOM Lotti in magazzino scadenza 30gg],
			    [PM Lotti in magazzino scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth\Lotti in magazzino scadenza 30gg
		lineageTag: 116ba5f7-57b2-47bd-b7a9-a4b1744a072b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYTD Lotti in magazzino scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [YTD Lotti in magazzino scadenza 30gg],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, YEAR ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Lotti in magazzino scadenza 30gg
		lineageTag: e9bbfa7f-e0dc-4d55-a1c6-6f8bfa9ffc64

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD Lotti in magazzino scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [YTD Lotti in magazzino scadenza 30gg]
			VAR __ValuePreviousPeriod = [PYTD Lotti in magazzino scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Lotti in magazzino scadenza 30gg
		lineageTag: 69489c5e-faec-46bd-b97f-e8a2faa5b96e

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YOYTD % Lotti in magazzino scadenza 30gg' = ```
			
			DIVIDE ( 
			    [YOYTD Lotti in magazzino scadenza 30gg],
			    [PYTD Lotti in magazzino scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Lotti in magazzino scadenza 30gg
		lineageTag: af29b732-0635-482a-a534-f59e553c7d63

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQTD Lotti in magazzino scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [QTD Lotti in magazzino scadenza 30gg],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, QUARTER ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Lotti in magazzino scadenza 30gg
		lineageTag: bd5427df-505c-4e0f-b886-f9e99f0f1327

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD Lotti in magazzino scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [QTD Lotti in magazzino scadenza 30gg]
			VAR __ValuePreviousPeriod = [PQTD Lotti in magazzino scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Lotti in magazzino scadenza 30gg
		lineageTag: 2889734d-915e-4d9a-801a-49f6e1be1951

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QOQTD % Lotti in magazzino scadenza 30gg' = ```
			
			DIVIDE ( 
			    [QOQTD Lotti in magazzino scadenza 30gg],
			    [PQTD Lotti in magazzino scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Lotti in magazzino scadenza 30gg
		lineageTag: 7ac152f6-7256-447d-860d-36227f860ca4

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMTD Lotti in magazzino scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MTD Lotti in magazzino scadenza 30gg],
			        CALCULATETABLE (
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            'Date'[DateWithTransactions] = TRUE
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Lotti in magazzino scadenza 30gg
		lineageTag: f204276d-1199-43bc-b016-f2859d441238

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD Lotti in magazzino scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [MTD Lotti in magazzino scadenza 30gg]
			VAR __ValuePreviousPeriod = [PMTD Lotti in magazzino scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\To-date growth\Lotti in magazzino scadenza 30gg
		lineageTag: 1dfeeecd-0744-48c2-a7ce-afd71ba04cf3

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MOMTD % Lotti in magazzino scadenza 30gg' = ```
			
			DIVIDE ( 
			    [MOMTD Lotti in magazzino scadenza 30gg],
			    [PMTD Lotti in magazzino scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\To-date growth\Lotti in magazzino scadenza 30gg
		lineageTag: 700834ec-5165-4bc2-9005-4e55fffa38eb

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYC Lotti in magazzino scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in magazzino scadenza 30gg],
			        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Lotti in magazzino scadenza 30gg
		lineageTag: bf9ed9c5-9b8a-418c-b92f-eb0cd4829c23

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YTDOPY Lotti in magazzino scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [YTD Lotti in magazzino scadenza 30gg]
			VAR __ValuePreviousPeriod = [PYC Lotti in magazzino scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Lotti in magazzino scadenza 30gg
		lineageTag: 2e33b09b-b344-45a2-9287-7389116e5e0a

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'YDTOPY % Lotti in magazzino scadenza 30gg' = ```
			
			DIVIDE ( 
			    [YTDOPY Lotti in magazzino scadenza 30gg],
			    [PYC Lotti in magazzino scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Lotti in magazzino scadenza 30gg
		lineageTag: ec8e7d4f-881f-44f1-ac97-c096c628ca98

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PQC Lotti in magazzino scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in magazzino scadenza 30gg],
			        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Lotti in magazzino scadenza 30gg
		lineageTag: 7e9ebaa4-cec5-40ae-9655-6ceaf8b95bff

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QTDOPQ Lotti in magazzino scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [QTD Lotti in magazzino scadenza 30gg]
			VAR __ValuePreviousPeriod = [PQC Lotti in magazzino scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Lotti in magazzino scadenza 30gg
		lineageTag: 6468dc65-df13-41d8-9098-2550cf45c209

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'QDTOPQ % Lotti in magazzino scadenza 30gg' = ```
			
			DIVIDE ( 
			    [QTDOPQ Lotti in magazzino scadenza 30gg],
			    [PQC Lotti in magazzino scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Lotti in magazzino scadenza 30gg
		lineageTag: 7da20cb4-8765-402f-a874-45b529d5f7b1

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PMC Lotti in magazzino scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in magazzino scadenza 30gg],
			        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Lotti in magazzino scadenza 30gg
		lineageTag: 1db305af-d3bb-4149-8d72-b4e0b5018cac

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM Lotti in magazzino scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [MTD Lotti in magazzino scadenza 30gg]
			VAR __ValuePreviousPeriod = [PMC Lotti in magazzino scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Growth over full period\Lotti in magazzino scadenza 30gg
		lineageTag: 28cd5a24-9fb9-4772-a201-5b8604c2dcac

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MTDOPM % Lotti in magazzino scadenza 30gg' = ```
			
			DIVIDE ( 
			    [MTDOPM Lotti in magazzino scadenza 30gg],
			    [PMC Lotti in magazzino scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Growth over full period\Lotti in magazzino scadenza 30gg
		lineageTag: b23947bf-34bd-40f0-ae59-e4b5a1591c40

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MAT Lotti in magazzino scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [Lotti in magazzino scadenza 30gg],
			        DATESINPERIOD (
			            'Date'[Date],
			            MAX ( 'Date'[Date] ),
			            -1,
			            YEAR
			        )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Lotti in magazzino scadenza 30gg
		lineageTag: a5c3576c-56a3-40a1-8af7-301bff84363b

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'PYMAT Lotti in magazzino scadenza 30gg' =
			
			IF (
			    [_ShowValueForDates],
			    CALCULATE (
			        [MAT Lotti in magazzino scadenza 30gg],
			        DATEADD ( 'Date'[Date], -1, YEAR )
			    )
			)
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Lotti in magazzino scadenza 30gg
		lineageTag: 5c3e1810-bdda-4314-a7ba-b7d607bd09d4

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG Lotti in magazzino scadenza 30gg' =
			
			VAR __ValueCurrentPeriod = [MAT Lotti in magazzino scadenza 30gg]
			VAR __ValuePreviousPeriod = [PYMAT Lotti in magazzino scadenza 30gg]
			VAR __Result =
			    IF (
			        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),
			        __ValueCurrentPeriod - __ValuePreviousPeriod
			    )
			RETURN
			    __Result
		formatString: 0
		displayFolder: Time intelligence\Moving annual growth\Lotti in magazzino scadenza 30gg
		lineageTag: 35a184ff-6c9c-4b12-a4d2-0a2a8b499b18

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'MATG % Lotti in magazzino scadenza 30gg' = ```
			
			DIVIDE ( 
			    [MATG Lotti in magazzino scadenza 30gg],
			    [PYMAT Lotti in magazzino scadenza 30gg]
			)
			```
		formatString: 0.00%
		displayFolder: Time intelligence\Moving annual growth\Lotti in magazzino scadenza 30gg
		lineageTag: 97da53c4-6b0c-4ad8-bf81-895cc31114d6

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	measure 'Litri raccolti' = sum(FattoRaccoltaLatte[Litri])
		formatString: 0
		lineageTag: f122b529-ebb5-49e3-a100-0104926ffe23

	measure '% Export' = DIVIDE(CALCULATE([Vendite],DimCanale[Canale]="Export"),[Vendite],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 57d6eb52-a2ea-4bf9-b29a-2d202a1033c8

	measure 'Valore magazzino FIFO' = sum(FattoMagazzino[ValoreFIFO])
		lineageTag: 0b0452cd-71d3-4c18-929f-c7aa96bb14af

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _
		isHidden
		formatString: 0
		lineageTag: 0bf9ffd9-bd14-435b-9572-a3a26bb03a81
		summarizeBy: sum
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition Misure = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 7c8018a0e1084fd0bf6a0f210bda928b

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

